# Generated by Django 3.2.3 on 2021-05-19 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(verbose_name='性别')),
                ('degree', models.CharField(max_length=10, verbose_name='学历')),
                ('origin', models.CharField(max_length=10, verbose_name='籍贯')),
                ('onJobTime', models.DateTimeField(auto_now_add=True, verbose_name='入职时间')),
            ],
            options={
                'db_table': 'storekeeper',
            },
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('capacity', models.PositiveIntegerField(verbose_name='容量')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('info', models.TextField(verbose_name='仓库信息')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='StoW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storekeeperId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.storekeeper')),
                ('warehouseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.warehouse')),
            ],
            options={
                'db_table': 'StoW',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('goodsClass', models.CharField(max_length=10, verbose_name='类别')),
                ('goodsInfo', models.TextField(verbose_name='货物信息')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('amount', models.PositiveIntegerField(verbose_name='剩余量')),
                ('warehouseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.warehouse')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
