# Generated by Django 3.2.3 on 2021-05-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='createTime',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goodsClass',
            new_name='goods_class',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goodsInfo',
            new_name='goods_info',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='warehouseId',
            new_name='warehouse_id',
        ),
        migrations.RenameField(
            model_name='stow',
            old_name='storekeeperId',
            new_name='storekeeper_id',
        ),
        migrations.RenameField(
            model_name='stow',
            old_name='warehouseId',
            new_name='warehouse_id',
        ),
    ]
