# Generated by Django 3.2.3 on 2021-05-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210519_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='goods_numbers',
            field=models.PositiveIntegerField(default=0, verbose_name='物品数'),
            preserve_default=False,
        ),
    ]
