# Generated by Django 3.2.3 on 2021-05-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_warehouse_goods_numbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goods',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='goods_class',
            new_name='good_class',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='goods_info',
            new_name='good_info',
        ),
    ]
