# Generated by Django 3.2.3 on 2021-05-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210519_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stow',
            old_name='storekeeper_id',
            new_name='storekeeper',
        ),
        migrations.RenameField(
            model_name='stow',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='good',
            name='warehouse_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.warehouse'),
        ),
    ]
