# Generated by Django 3.2.3 on 2021-05-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210519_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.warehouse'),
        ),
    ]
