# Generated by Django 3.2.3 on 2021-05-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_good_warehouse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='warehouse_name',
        ),
    ]
