# Generated by Django 3.2.3 on 2021-05-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_good_warehouse_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
    ]
