# Generated by Django 3.2.3 on 2021-05-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_warehouse_id_good_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.warehouse'),
        ),
    ]
